export default [
	{
		name:"Chinmay Patil",
		rating:5,
		employer:"CICS Careers",
		title:"Career Developer",
		location:"A243 LGRC Lowrise",
		topics: ["Mock Interview","Resume Review","Job Search","Cover Letter"],
		tags: ["React", "Machine Learning","iOS","React", "C++","HTML","CSS", "x86 Assembly","320","Project Managing", "UI Design","UX Design","Natrual Language Processing", "Typography","OSX","Vim", "Git","Angular"],
		imgsrc: 'https://www.cics.umass.edu/sites/default/files/styles/people_individual/public/headshots/img_4695_copy.jpg?itok=jwwJF0KP',
		timeBlocks: [{start: "08:00", end: "10:00"},{start: "11:00", end:"16:00"}],
		day: "04/18/2020",
		linkedin: "https://www.linkedin.com/in/chinmayspatil/",
		id:1
	},
	{
		name:"Dhruvil Gala",
		rating:4,
		employer:"CICS Careers",
		title:"Career Developer",
		location:"A243 LGRC Lowrise",
		topics: ["Mock Interview","Resume Review","Cover Letter","Job Search"],
		tags: ["AWS", "Microsoft","Algorithms","AWS"],
		imgsrc: 'https://www.cics.umass.edu/sites/default/files/styles/people_individual/public/headshots/image2_001.jpg?itok=ogGUoKuq',
		timeBlocks: [{start: "08:00", end: "10:00"},{start: "12:00", end:"13:00"}],
		day: "04/18/2020",
		linkedin: "https://www.linkedin.com/in/dhruvilgala/",
		id: 2
	},
	{
		name:"Brian Krusell",
		rating:4.5,
		employer:"CICS Careers",
		title:"Director of Career & Student Development",
		location:"A213 LGRC Lowrise",
		topics: ["Resume Review","Job Search","Cover Letter"],
		tags: ["Industry", "Networking"],
		imgsrc: 'https://www.cics.umass.edu/sites/default/files/styles/people_individual/public/headshots/krusell.jpg?itok=tjD9O0Rp',
		timeBlocks: [{start: "08:00", end: "10:00"},{start: "13:00", end:"14:00"}],
		day: "04/18/2020",
		linkedin: "https://www.linkedin.com/in/briankrusell/detail/recent-activity/posts/",
		id:3
	},
	{
		name:"David Fisher",
		rating:5,
		employer:"UMass Amherst",
		title:"Professor",
		location:"A267 LGRC",
		topics: ["Demo Prep", "Homework Help"],
		tags: ["Search Engines", "The Process","Pitchfork vs Torch","Project Managing","320"],
		imgsrc: 'https://www.cics.umass.edu/sites/default/files/styles/people_individual/public/headshots/fisherdavid.jpg?itok=VHwskVUz',
		timeBlocks: [{start: "16:00", end: "17:30"}],
		day: "04/18/2020",
		linkedin: "",
		id:4
	},
	{
		name:"Dale Osef",
		rating:4.5,
		employer:"UMass Amherst",
		title:"Assistant Director of Career Development",
		location:"A213 LGRC",
		topics: ["Mock Interview","Resume Review","Job Search"],
		tags: ["Networking","Career Development"],
		imgsrc: 'https://www.cics.umass.edu/sites/default/files/styles/people_individual/public/headshots/professional_photo_osef_bio_sq_0.jpeg?itok=Rbw5wK83',
		timeBlocks: [{start: "07:00", end: "19:00"}],
		day: "04/18/2020",
		linkedin: "https://www.linkedin.com/in/daleosef/",
		id:5
	},
	{
		name:"Elizabeth Parolski",
		rating:5,
		employer:"UMass Amherst",
		title:"Academic Advisor - MS Program",
		location:"A243 LGRC Lowrise",
		topics: ["Graduate School Help","Resume Review","Job Search"],
		tags: ["Masters","Bay State", "PhD", "Career Development"],
		imgsrc: 'https://www.cics.umass.edu/sites/default/files/styles/people_individual/public/headshots/ep.jpg?itok=6T9WERKd',
		timeBlocks: [{start: "08:00", end: "08:30"},{start: "10:00", end: "10:30"},{start: "13:30", end: "14:30"}],
		day: "04/18/2020",
		linkedin: "https://www.linkedin.com/in/elizabeth-parolski-0ba9184a/",
		id:6
	},
	{
		name:"David Barrington",
		rating:3.5,
		employer:"UMass Amherst",
		title:"Professor",
		location:"210 CS Building",
		topics: ["Homework Help"],
		tags: ["Discrete Math", "Algorithms","Combinatorics"],
		imgsrc: 'https://people.cs.umass.edu/~barring/david_3.jpg',
		timeBlocks: [{start: "08:00", end: "10:00"},{start: "13:00", end:"14:00"}],
		day: "04/18/2020",
		linkedin: "",
		id:6
	},
	{
		name:"Sam the Minuteman",
		rating:3,
		employer:"UMass Amherst",
		title:"Influencer",
		location:"Mullins Center",
		topics: ["Hype","Giving Pizza"],
		tags: ["Basketball", "Hockey","Football"],
		imgsrc: 'https://www.umass.edu/newsoffice/sites/default/files/styles/article_medium/public/Sam.jpg',
		timeBlocks: [{start: "8:00", end: "10:00"},{start: "11:00", end:"13:00"}],
		day: "04/18/2020",
		linkedin: "",
		id:7
	},
]